from fpdf import FPDF
from datetime import datetime
import os

class ProctoringReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'SmartProctor AI - Automated Examination Report', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'R')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(session_data, logs, output_path):
    print(f"DEBUG: Starting PDF generation for {output_path}")
    try:
        pdf = ProctoringReport()
        pdf.add_page()
        
        # Session Details
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'Candidate Details', 0, 1, 'L')
        pdf.set_font('Arial', '', 11)
        
        details = [
            ('Candidate Name', str(session_data.get('candidateName', 'N/A'))),
            ('Candidate ID', str(session_data.get('candidateId', 'N/A'))),
            ('Exam Title', str(session_data.get('examTitle', 'N/A'))),
            ('Exam Code', str(session_data.get('examCode', 'N/A'))),
            ('Exam Center', str(session_data.get('center', 'N/A'))),
            ('Seat Number', str(session_data.get('seatNumber', 'N/A'))),
            ('Total Violations', str(len(logs)))
        ]
        
        for label, value in details:
            pdf.cell(50, 8, f'{label}:', 0, 0)
            pdf.cell(0, 8, value, 0, 1)
        
        pdf.ln(10)
        
        # Violation Logs
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'Violation History', 0, 1, 'L')
        
        if not logs:
            pdf.set_font('Arial', 'I', 10)
            pdf.cell(0, 10, 'No violations recorded during this session.', 0, 1, 'L')
        else:
            pdf.set_font('Arial', 'B', 10)
            # Table Header
            pdf.cell(10, 8, 'ID', 1, 0, 'C')
            pdf.cell(40, 8, 'Timestamp', 1, 0, 'C')
            pdf.cell(40, 8, 'Type', 1, 0, 'C')
            pdf.cell(0, 8, 'Description', 1, 1, 'C')
            
            pdf.set_font('Arial', '', 9)
            for log in logs:
                try:
                    ts = str(log.get('timestamp', 'N/A')).split('T')[1].split('.')[0] if 'T' in str(log.get('timestamp', '')) else 'N/A'
                    pdf.cell(10, 8, str(log.get('id', '?')), 1, 0, 'C')
                    pdf.cell(40, 8, ts, 1, 0, 'C')
                    pdf.cell(40, 8, str(log.get('type', 'N/A')), 1, 0, 'C')
                    pdf.cell(0, 8, str(log.get('description', 'N/A')), 1, 1, 'L')
                except Exception as e:
                    print(f"DEBUG: Error writing log entry: {e}")
                    continue

        pdf.ln(10)
        pdf.set_font('Arial', 'I', 10)
        pdf.multi_cell(0, 10, "Note: This report was automatically generated by SmartProctor AI. Critical violations are flagged for review.")
        
        pdf.output(output_path)
        print(f"DEBUG: PDF successfully saved to {output_path}")
        return output_path
    except Exception as e:
        print(f"DEBUG: CRITICAL PDF GENERATION ERROR: {str(e)}")
        import traceback
        traceback.print_exc()
        raise e
